### ISSUE TITLE
/teams/2020 KeyError

### ISSUE THREAD

**Issue by gabekutner** [gabekutner/pll_stats_api#9]
When accessing /teams/2020 endpoint, the following is thrown
Traceback (most recent call last)
File "/Users/gabekutner/Documents/GitHub/pll_stats_api/main.py", line 79, in get_all_teams
    datastorage.init(year)
  File "/Users/gabekutner/Documents/GitHub/pll_stats_api/datastorage.py", line 51, in init
    _load_players(year, season)
  File "/Users/gabekutner/Documents/GitHub/pll_stats_api/datastorage.py", line 105, in _load_players
    stats = _get_model(row, 'Position')
  File "/Users/gabekutner/Documents/GitHub/pll_stats_api/datastorage.py", line 187, in _get_model
    model = data[row[c]]
KeyError: 'Position'

The program runs fine with /teams/2022 and /2021

**Comment by gabekutner** [comment]
Fixed
When I initialized `datastorage` in /teams/{year} I didn't pass a season bcuz there is no season parameter for retrieving teams stats. Bcuz initializing `datastorage` calls `_load_players()` which does take a season parameter, an error is thrown bcuz the function can't run without a season.

To fix it, I added an optional query parameter to /teams/2020, set the default to 'regular', and passed into `datastorage.init `. This lets `_load_players()` run without error.

**Comment by gabekutner** [comment]
On second thought, I should later make two different modules, one for _teams and the other for _players.
Right now, I call both load functions when I'm using only either teams or players. A good amount of run time is taken up here, so make two different modules -> this is put into new issue(tags=enhancements)
